name: Build and Deploy

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Common env for jobs
env:
  DUMMY: World-1!

jobs:
  build:
    # Build runs on staging runner
    runs-on: ubuntu-latest
    name: Compile and Package
    env:
      DUMMY1: Hello-2
    steps:
      - uses: actions/checkout@v4.1.5
      - name: Push latest tags (if on main branch)
        run: |
           echo "Hello $DUMMY"
      - name: Push latest tags (if on main branch)
        run: |
           echo "Hello $DUMMY1"
  deployment-staging:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: deploy
        run: |
           echo "Deploying staging"
  deployment-prod:
    runs-on: ubuntu-latest
    environment: production-eu
    steps:
      - name: deploy
        run: |
           echo "Deploying prod"
